### PR TITLE
Try building v86 on Travis

### PR DESCRIPTION
**Pull request by humphd**
This is an experiment to see what I can do on Travis in order to (re)build our v86 Linux ISO.

### CODE REVIEW

**Comment by humphd** [comment]
I finally got this build to work.  It required a bunch of hacks to get Travis to not timeout, deal with not filling the 4M build log and failing, etc.

In the end, the buildroot compile (not including `docker build`, which is pretty fast, but adds more time) step takes 45 mins, and we have a max of 50 mins for a build to complete on Travis.

I think we're going to have to come up with another solution.

**Comment by dsych** [comment]
The only other way I see is doing manual releases on PRs that modify buildroot files.

**Comment by dsych** [comment]
One other idea,is there any way for us to only build certain parts of the OS based on the changes in config files with buildroot. E.g. if kernel config changes, only build it and include new version in the bundle.

**Comment by humphd** [comment]
If we didn't do the build in Docker, we could cache the build artifacts with Travis, and then reuse them.  But honestly, at some point you have to do a full build (1st build, for example), and we simply don't have enough time without a paid account.

I wonder if we should do this manually, and stick the build binary files (bios, vgabios, linux ISO) in [`git lfs`](https://git-lfs.github.com/).  That seems like it might work, and github/travis can both use it to get the built files.  I've never used it, but this might be a good time to learn!

Since they won't change often, managing it manually should be OK.

**Pull request closed without merging**
